version: "3"
services:

  reqbaz-backend:
    build:
      context: ./reqbaz-backend
    links:
      - reqbaz-mysql:mysql
    ports:
      - 8080:8080

  reqbaz-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: reqbaz
      MYSQL_DATABASE: reqbaz
    expose:
      - 3306

  reqbaz-frontend:
    build:
      context: ./reqbaz-frontend
    links:
      - reqbaz-backend:backend
    ports:
      - 8081:8081

  activity-tracker:
    build:
      context: ./activity-tracker
    links:
      - reqbaz-backend:reqbaz-backend
      - activity-tracker-mysql:mysql

  activity-tracker-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: reqbaz
      MYSQL_DATABASE: reqbaztrack
    expose:
      - 3306

  file-service:
    build:
      context: ./file-service
    links:
      - reqbaz-backend:reqbaz-backend