version: "3"
services:

  reqbaz-backend:
    build:
      context: ./reqbaz-backend/repo
    links:
      - reqbaz-mysql:mysql
      - mobsos-data-processing:mobsos-data-processing
    environment:
      BOOTSTRAP: mobsos-data-processing:9011
      MYSQL_USER: reqbaz
      MYSQL_PASSWORD: reqbaz
      INSERT_DEMO_DATA_FULL: 'true'
      ACTIVITY_TRACKER_SERVICE: 'de.rwth.dbis.acis.activitytracker.service.ActivityTrackerService@*'
      SERVICE_EXTRA_ARGS: '--observer'
    ports:
      - 8080:8080
    restart: always

  reqbaz-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: reqbaz
      MYSQL_USER: reqbaz
      MYSQL_PASSWORD: reqbaz
      MYSQL_DATABASE: reqbaz
    expose:
      - 3306
    restart: always

  reqbaz-frontend:
    build:
      context: ./reqbaz-frontend
    links:
      - reqbaz-backend:backend
    ports:
      - 8081:8081
    restart: always

  activity-tracker:
    image: rwthacis/las2peer-activity-tracker:develop
    environment:
      BOOTSTRAP: mobsos-data-processing:9011
      MYSQL_USER: activity_tracker
      MYSQL_PASSWORD: activity_tracker
      INSERT_DEMO_DATA: 'true'
      #SERVICE_EXTRA_ARGS: '--observer'
      #DEBUG: 'true'
    links:
      - mobsos-data-processing:mobsos-data-processing
      - activity-tracker-mysql:mysql
    restart: always

  activity-tracker-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: activity_tracker
      MYSQL_USER: activity_tracker
      MYSQL_PASSWORD: activity_tracker
      MYSQL_DATABASE: reqbaztrack
    expose:
      - 3306
    restart: always

  file-service:
    image: rwthacis/las2peer-file-service:develop
    environment:
      BOOTSTRAP: mobsos-data-processing:9011
      SERVICE_EXTRA_ARGS: '--observer'
    links:
      - mobsos-data-processing:mobsos-data-processing
    restart: always

  mobsos-data-processing:
    image: rwthacis/mobsos-data-processing:develop
    environment:
      MYSQL_USER: mobsos
      MYSQL_PASSWORD: mobsos
    links:
      - mobsos-data-processing-mysql:mysql
    restart: always

  mobsos-success-modeling:
    image: rwthacis/mobsos-success-modeling:develop
    environment:
      MYSQL_USER: mobsos
      MYSQL_PASSWORD: mobsos
      BOOTSTRAP: mobsos-data-processing:9011
      USE_FILE_SERVICE: 'TRUE'
      SERVICE_EXTRA_ARGS: '--observer'
    links:
      - mobsos-data-processing:mobsos-data-processing
      - mobsos-data-processing-mysql:mysql
    restart: always

  mobsos-data-processing-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mobsos
      MYSQL_USER: mobsos
      MYSQL_PASSWORD: mobsos
      MYSQL_DATABASE: LAS2PEERMON
    expose:
      - 3306
    restart: always

  mobsos-surveys:
    image: rwthacis/mobsos-surveys:develop
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: mobsos
      OIDC_CLIENT_ID: 2fbca3ef-babc-431b-ac61-f99967228552
      BOOTSTRAP: mobsos-data-processing:9011
      SERVICE_EXTRA_ARGS: '--observer'
    links:
      - mobsos-data-processing:mobsos-data-processing
      - mobsos-surveys-mysql:mysql
    restart: always

  mobsos-surveys-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mobsos
      MYSQL_DATABASE: mobsos
    expose:
      - 3306
    restart: always

  mobsos-query-visualization:
    image: rwthacis/mobsos-query-visualization:development
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: mobsos
      INIT_EXAMPLE_DATABASE: 'true'
      MYSQL_EXAMPLE_USER: root
      MYSQL_EXAMPLE_PASSWORD: mobsos
      BOOTSTRAP: mobsos-data-processing:9011
      SERVICE_EXTRA_ARGS: '--observer'
    links:
      - mobsos-data-processing:mobsos-data-processing
      - mobsos-query-visualization-mysql:mysql
    restart: always

  mobsos-query-visualization-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mobsos
      MYSQL_DATABASE: QVS
    expose:
      - 3306
    restart: always

  cae-code-generation-service:
    image: rwthacis/cae-code-generation-service
    environment:
      GIT_USER: ${GIT_USER}
      GIT_PASSWORD: ${GIT_PASSWORD}
      GIT_USER_MAIL: ${GIT_USER_MAIL}
      GIT_ORGANIZATION: ${GIT_ORGANIZATION}
      BOOTSTRAP: mobsos-data-processing:9011
      SERVICE_EXTRA_ARGS: '--observer'
    links:
      - mobsos-data-processing:mobsos-data-processing
    restart: always

  cae-model-persistence-service:
    image: rwthacis/cae-model-persistence-service:latest
    environment:
      MYSQL_USER: cae
      MYSQL_PASSWORD: cae
      INIT_WIREFRAME_EXTENSION: 'true'
      BOOTSTRAP: mobsos-data-processing:9011
      SERVICE_EXTRA_ARGS: '--observer'
    links:
      - mobsos-data-processing:mobsos-data-processing
      - cae-model-persistence-service-mysql:mysql
    restart: always

  cae-model-persistence-service-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: cae
      MYSQL_USER: cae
      MYSQL_PASSWORD: cae
      MYSQL_DATABASE: commedit
    expose:
      - 3306
    restart: always

  role-sdk:
    image: rwthacis/role-sdk:latest
    links:
      - cae-model-persistence-service:cae-model-persistence-service
      - cae-code-generation-service:cae-code-generation-service
    ports:
      - 8073:8073
    restart: always

  adminer:
    image: adminer
    links:
      - mobsos-data-processing-mysql:processing-db
      - activity-tracker-mysql:activity-db
    ports:
      - 8082:8080
    restart: always